+spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogs
    username: root
    password: Pass@123

  jpa:
    hibernate:
      ddl-auto: update
    #      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true